[package]
name = "nickel-gc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel-gc-derive = { path = "../nickel-gc-derive" }

