[package]
name = "nls"
version = "0.1.0"
authors = ["Nicl team"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Programmable configuration files."
edition = "2018"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
codespan = "0.11"
codespan-reporting = "0.11"
codespan-lsp = "0.11"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
structopt = "0.3"


lsp-server = "0.5"
lsp-types = "0.88"
log = "0.4"
env_logger = "0.9"
anyhow = "1.0"
nickel = {path = "../../"}
derive_more = "0.99"
lazy_static = "1"
csv = "1"

[dev-dependencies]
pretty_assertions = "0.5.1"
assert_matches = "1.4.0"
