name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  run-benchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: jasonwilliams/criterion-compare-action@move_to_actions

  build-and-test:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust_channel:
          - stable
          - beta
          - nightly
        include:
          - os: ubuntu-latest
            system: x86_64-linux
            experimental: false
          - os: macos-latest
            system: x86_64-darwin
            experimental: false
          - rust_channel: nightly
            experimental: true

    runs-on: ${{ matrix.os }}
    # The `== true` makes it work wether experimental has been defined or not.
    continue-on-error: ${{ matrix.experimental == true }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nickel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Building Nickel against `${{ matrix.rust_channel }}` Rust channel
      run: |
        nix build ./#checks.${{ matrix.system }}.nickel-against-${{ matrix.rust_channel }}-rust-channel
